Skapa-Alerts-Komponenten#11
io-berg/Webbshop-grupp2 pull request #56
Opened 2022-09-07 11:33 UTC by Ola-Larsson

Skapat en snackbar context, som visar medelanden man själv kan ställa in, som inte pausar det andra i UI

2022-09-07 11:44 UTC, io-berg commented on src/App.tsx
> +    <SnackProvider>
Flytta denna till Main istället, ska göra samma med ProductProvider

2022-09-07 11:44 UTC, io-berg commented on src/components/SnackBar.tsx
> +    </Snackbar>
Går det göra så att man kan ha flera snack sammtidigt? typ om man spammar add to cart

2022-09-07 11:44 UTC, io-berg commented on src/pages/AdminPage.tsx
> +        <SnackBarComponent />
Eftersom vi vill kunna se alerts lite överallt kan vi väl bara lägga denna i Layout

2022-09-07 13:55 UTC, Ola-Larsson commented on src/components/SnackBar.tsx
> +    </Snackbar>
tror detta funkar

2022-09-07 18:46 UTC, io-berg commented on src/components/SnackBar.tsx
> +    </Snackbar>
Läst lite mer om detta och dom säger att man inte skall använda flera snackbars.. 
https://github.com/mui/material-ui/issues/1824

Så vi borde nog nöja oss med att bara ha en, my bad.

2022-09-07 19:41 UTC, io-berg requested changes

2022-09-07 19:41 UTC, io-berg commented on src/components/SnackBar.tsx
> +    </div>
```suggestion
    <Snackbar
      open={snack.open}
      autoHideDuration={3000}
      onClose={(e, r) => handleClose(r)}
    >
      <Alert
        severity={snack.color}
        sx={{ width: "100%" }}
        onClose={() => handleClose()}
      >
        {snack.message}
      </Alert>
    </Snackbar>
```

Om vi ska bara visa upp 1 alert igen

2022-09-07 19:41 UTC, io-berg commented on src/contexts/SnackContext.tsx
> +  };
```suggestion
interface ContextValue {
  snack: Snack;
  addNewSnack: (snack: Snack) => void;
  handleClose: (reason?: string) => void;
}

const SnackContext = createContext<ContextValue>({
  snack: {
    message: "You forgot to add the SnackProvider",
    color: "error",
    open: true,
  },
  addNewSnack: () => {
    console.log("You forgot to add the SnackProvider");
  },
  handleClose: () => {
    console.log("något gick fel");
  },
});

interface Props {
  children: ReactNode;
}

function SnackProvider({ children }: Props) {
  const [snack, setSnack] = useState<Snack>({
    message: "",
    color: "error",
    open: false,
  });

  const handleClose = (reason?: string) => {
    if (reason === "clickaway") return;

    setSnack({ ...snack, open: false });
  };

  const addNewSnack = (snack: Snack) => {
    setSnack(snack);
  };
```

Detta är också om vi vill ändra tillbaka till att bara ha 1 snack.
Plus en liten fix på en sak jag märkte, när man hade en snack uppe och försökte öppna en till så försvann båda.

2022-09-08 07:00 UTC, Ola-Larsson commented on src/components/SnackBar.tsx
> +    </Snackbar>
Vi kan byta tillbaka isåfall. Jag tror inte att det ska vara ett problem. Fixar det 👍

2022-09-08 07:23 UTC, io-berg approved these changes
Look good

2022-09-08 07:24 UTC, merged